// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDilZkX0knw_Kc61tZ0iLsN17eCcYFR4CI',
    appId: '1:163343728948:web:168da4ae2c85da6ad2e561',
    messagingSenderId: '163343728948',
    projectId: 'flashchat-fbdfc',
    authDomain: 'flashchat-fbdfc.firebaseapp.com',
    storageBucket: 'flashchat-fbdfc.appspot.com',
    measurementId: 'G-1Y663T9WYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuss-hclfPE9ulLQUWWT5gh7wqSeVLJxg',
    appId: '1:163343728948:android:1f51156739a08fb6d2e561',
    messagingSenderId: '163343728948',
    projectId: 'flashchat-fbdfc',
    storageBucket: 'flashchat-fbdfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh-UNV853aSdpSJWcKjxmSqoX9NOpM1Kk',
    appId: '1:163343728948:ios:aefef4943cb5f0a1d2e561',
    messagingSenderId: '163343728948',
    projectId: 'flashchat-fbdfc',
    storageBucket: 'flashchat-fbdfc.appspot.com',
    iosClientId: '163343728948-t35kuki53097211u5g8af2m6ofb4q8mp.apps.googleusercontent.com',
    iosBundleId: 'chatApp.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh-UNV853aSdpSJWcKjxmSqoX9NOpM1Kk',
    appId: '1:163343728948:ios:aefef4943cb5f0a1d2e561',
    messagingSenderId: '163343728948',
    projectId: 'flashchat-fbdfc',
    storageBucket: 'flashchat-fbdfc.appspot.com',
    iosClientId: '163343728948-t35kuki53097211u5g8af2m6ofb4q8mp.apps.googleusercontent.com',
    iosBundleId: 'chatApp.chatApp',
  );
}
